// <auto-generated />
using System;
using Iemas.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Iemas.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260922031629_AddEscalations")]
    partial class AddEscalations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Iemas.Domain.Agents.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentVersion")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ConnectionStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceMetadata")
                        .HasColumnType("text");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("EnrollmentEmailAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset?>("LastConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastKnownClientIp")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RegistrationRequestToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RegistrationStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("RevocationReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServerAddress")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RegistrationRequestToken")
                        .IsUnique();

                    b.HasIndex("RegistrationStatus");

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("Iemas.Domain.Agents.AgentCaseAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CaseEventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ClientTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("ServerTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("AgentId", "RequestId")
                        .IsUnique();

                    b.ToTable("agent_case_actions", (string)null);
                });

            modelBuilder.Entity("Iemas.Domain.Agents.AgentCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("PendingKeyCiphertext")
                        .HasColumnType("bytea");

                    b.Property<string>("PendingKeyEncryptionKeyId")
                        .HasColumnType("text");

                    b.Property<byte[]>("PendingKeyNonce")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PendingKeyTag")
                        .HasColumnType("bytea");

                    b.Property<bool>("RawKeyCollected")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RotatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgentId")
                        .IsUnique();

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.ToTable("agent_credentials", (string)null);
                });

            modelBuilder.Entity("Iemas.Domain.Agents.AgentLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("OccurredAt");

                    b.ToTable("agent_logs", (string)null);
                });

            modelBuilder.Entity("Iemas.Domain.Ai.AiClassificationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiModel")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<Guid>("EmailMessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmailMessageId");

                    b.ToTable("ai_classification_logs", (string)null);
                });

            modelBuilder.Entity("Iemas.Domain.Ai.AiModelConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigurationMetadata")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<int>("FallbackOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("integer");

                    b.Property<string>("ModelIdentifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TaskCapability")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TaskCapability");

                    b.HasIndex("Provider", "ModelIdentifier")
                        .IsUnique();

                    b.ToTable("ai_model_configs", (string)null);
                });

            modelBuilder.Entity("Iemas.Domain.Ai.ClassificationProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ExampleContent")
                        .HasColumnType("text");

                    b.Property<string>("ExampleSubject")
                        .HasColumnType("text");

                    b.Property<string>("ExcludeDefinitions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExpectedClassification")
                        .HasColumnType("text");

                    b.Property<double?>("HighConfidenceThreshold")
                        .HasColumnType("double precision");

                    b.Property<string>("IncludeDefinitions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("MediumConfidenceThreshold")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool?>("TreatMediumConfidenceAsReviewRequired")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("classification_profiles", (string)null);
                });

            modelBuilder.Entity("Iemas.Domain.Ai.EmailClassification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("ActionRequired")
                        .HasColumnType("boolean");

                    b.Property<double?>("AiConfidence")
                        .HasColumnType("double precision");

                    b.Property<string>("AiModel")
                        .HasColumnType("text");

                    b.Property<string>("AiProvider")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<Guid?>("ClassificationProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ClassifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ConfidenceBand")
                        .HasColumnType("integer");

                    b.Property<string>("CorrectedCategory")
                        .HasColumnType("text");

                    b.Property<int?>("CorrectedPriority")
                        .HasColumnType("integer");

                    b.Property<int?>("CorrectedRelevance")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Decision")
                        .HasColumnType("integer");

                    b.Property<string>("DecisionReason")
                        .HasColumnType("text");

                    b.Property<bool>("DeterministicFilterMatched")
                        .HasColumnType("boolean");

                    b.Property<string>("DeterministicFilterReason")
                        .HasColumnType("text");

                    b.Property<Guid>("EmailMessageId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsManuallyCorrected")
                        .HasColumnType("boolean");

                    b.Property<int?>("Priority")
                        .HasColumnType("integer");

                    b.Property<long?>("ProcessingDurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ProcessingError")
                        .HasColumnType("text");

                    b.Property<string>("PromptProfileVersion")
                        .HasColumnType("text");

                    b.Property<int?>("Relevance")
                        .HasColumnType("integer");

                    b.Property<bool?>("ResponseExpected")
                        .HasColumnType("boolean");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClassificationProfileId");

                    b.HasIndex("Decision");

                    b.HasIndex("EmailMessageId")
                        .IsUnique();

                    b.ToTable("email_classifications", (string)null);
                });

            modelBuilder.Entity("Iemas.Domain.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserEmail")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Iemas.Domain.Cases.Case", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompletionComment")
                        .HasColumnType("text");

                    b.Property<int?>("CompletionReason")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("CustomerEmailAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid>("EmailAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FirstEmailReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedSubject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NotificationStatus")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OwnerEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReopenCount")
                        .HasColumnType("integer");

                    b.Property<int>("ReplyStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WorkStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CaseNumber")
                        .IsUnique();

                    b.HasIndex("CustomerEmailAddress");

                    b.HasIndex("NormalizedSubject");

                    b.HasIndex("OwnerEmployeeId");

                    b.HasIndex("WorkStatus");

                    b.HasIndex("EmailAccountId", "CustomerEmailAddress");

                    b.ToTable("cases", (string)null);
                });

            modelBuilder.Entity("Iemas.Domain.Cases.CaseEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmailMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MatchDetail")
                        .HasColumnType("text");

                    b.Property<int>("MatchSignal")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("EmailMessageId")
                        .IsUnique();

                    b.ToTable("case_emails", (string)null);
                });

            modelBuilder.Entity("Iemas.Domain.Cases.CaseEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("OccurredAt");

                    b.ToTable("case_events", (string)null);
                });

            modelBuilder.Entity("Iemas.Domain.Cases.ReplyVerificationAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorDetail")
                        .HasColumnType("text");

                    b.Property<string>("MatchDetail")
                        .HasColumnType("text");

                    b.Property<int>("MatchSignal")
                        .HasColumnType("integer");

                    b.Property<string>("MatchedSentMessageId")
                        .HasColumnType("text");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAt");

                    b.HasIndex("CaseId");

                    b.ToTable("reply_verification_attempts", (string)null);
                });

            modelBuilder.Entity("Iemas.Domain.Email.EmailAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AuthMethod")
                        .HasColumnType("integer");

                    b.Property<string>("ClassificationProfileName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Encryption")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("LastTestError")
                        .HasColumnType("text");

                    b.Property<bool?>("LastTestSucceeded")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastTestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MonitoringEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OwnerEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<int>("Protocol")
                        .HasColumnType("integer");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerEmployeeId");

                    b.HasIndex("EmailAddress", "Purpose")
                        .IsUnique();

                    b.ToTable("email_accounts", (string)null);
                });

            modelBuilder.Entity("Iemas.Domain.Email.EmailAttachmentMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmailMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmailMessageId");

                    b.ToTable("email_attachment_metadata", (string)null);
                });

            modelBuilder.Entity("Iemas.Domain.Email.EmailCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmailAccountId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("EncryptedSecret")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("RotatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Tag")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmailAccountId")
                        .IsUnique();

                    b.ToTable("email_credentials", (string)null);
                });

            modelBuilder.Entity("Iemas.Domain.Email.EmailIntakeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<Guid>("EmailAccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderMessageId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EmailAccountId", "CreatedAt");

                    b.ToTable("email_intake_logs", (string)null);
                });

            modelBuilder.Entity("Iemas.Domain.Email.EmailMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("AiConfidence")
                        .HasColumnType("double precision");

                    b.Property<string>("AiModel")
                        .HasColumnType("text");

                    b.Property<int>("AttachmentCount")
                        .HasColumnType("integer");

                    b.Property<string>("BodyHtml")
                        .HasColumnType("text");

                    b.Property<string>("BodyText")
                        .HasColumnType("text");

                    b.Property<Guid?>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("CcAddresses")
                        .HasColumnType("text");

                    b.Property<string>("Classification")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmailAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("FromDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("InReplyTo")
                        .HasColumnType("text");

                    b.Property<string>("MessageId")
                        .HasColumnType("text");

                    b.Property<string>("ProcessingError")
                        .HasColumnType("text");

                    b.Property<int>("ProcessingStatus")
                        .HasColumnType("integer");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<string>("ProviderMessageId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("References")
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThreadId")
                        .HasColumnType("text");

                    b.Property<string>("ToAddresses")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InReplyTo");

                    b.HasIndex("MessageId");

                    b.HasIndex("ProcessingStatus");

                    b.HasIndex("ReceivedAt");

                    b.HasIndex("ThreadId");

                    b.HasIndex("EmailAccountId", "ProviderMessageId")
                        .IsUnique();

                    b.ToTable("email_messages", (string)null);
                });

            modelBuilder.Entity("Iemas.Domain.Email.EmailSyncState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConsecutiveFailureCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmailAccountId")
                        .HasColumnType("uuid");

                    b.Property<long?>("LastSeenUid")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("LastSyncCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastSyncError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastSyncStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastUidValidity")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmailAccountId")
                        .IsUnique();

                    b.ToTable("email_sync_states", (string)null);
                });

            modelBuilder.Entity("Iemas.Domain.Escalations.EscalationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryResult")
                        .HasColumnType("text");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<string>("EmailMessageId")
                        .HasColumnType("text");

                    b.Property<Guid?>("EscalationPolicyId")
                        .HasColumnType("uuid");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<string>("RecipientDisplay")
                        .HasColumnType("text");

                    b.Property<Guid?>("RecipientEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RecipientType")
                        .HasColumnType("integer");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<int?>("SkipReason")
                        .HasColumnType("integer");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("EscalationPolicyId");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("CaseId", "EscalationPolicyId", "Level", "Outcome");

                    b.ToTable("escalation_events", (string)null);
                });

            modelBuilder.Entity("Iemas.Domain.Escalations.EscalationGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("escalation_groups", (string)null);
                });

            modelBuilder.Entity("Iemas.Domain.Escalations.EscalationGroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EscalationGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EscalationGroupId", "EmployeeId")
                        .IsUnique();

                    b.ToTable("escalation_group_members", (string)null);
                });

            modelBuilder.Entity("Iemas.Domain.Escalations.EscalationLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("DelayAfterPreviousLevel")
                        .HasColumnType("interval");

                    b.Property<Guid>("EscalationPolicyId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("RecipientType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SpecificEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SpecificGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SpecificEmployeeId");

                    b.HasIndex("SpecificGroupId");

                    b.HasIndex("EscalationPolicyId", "Level")
                        .IsUnique();

                    b.ToTable("escalation_levels", (string)null);
                });

            modelBuilder.Entity("Iemas.Domain.Escalations.EscalationPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categories")
                        .HasColumnType("text");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("ClassificationProfileId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("Cooldown")
                        .HasColumnType("interval");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan>("GracePeriod")
                        .HasColumnType("interval");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<int>("MaximumLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("TriggerReminderCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClassificationProfileId");

                    b.HasIndex("IsDefault");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("escalation_policies", (string)null);
                });

            modelBuilder.Entity("Iemas.Domain.Identity.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("ManagerEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManagerEmployeeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("Iemas.Domain.Identity.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("SupervisorEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SupervisorEmployeeId");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("Iemas.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Iemas.Domain.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Iemas.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Iemas.Domain.Identity.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Iemas.Domain.Reminders.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CancelDetail")
                        .HasColumnType("text");

                    b.Property<int?>("CancelReason")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliveryAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ExecutedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExecutionClaimToken")
                        .HasColumnType("text");

                    b.Property<string>("LastFailureDetail")
                        .HasColumnType("text");

                    b.Property<Guid?>("ReminderPolicyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RequestedForUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ScheduledForUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SourceAgentCaseActionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Trigger")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("ExecutionClaimToken")
                        .IsUnique();

                    b.HasIndex("ReminderPolicyId");

                    b.HasIndex("SourceAgentCaseActionId")
                        .IsUnique()
                        .HasFilter("\"SourceAgentCaseActionId\" IS NOT NULL");

                    b.HasIndex("Status", "ScheduledForUtc");

                    b.ToTable("reminders", (string)null);
                });

            modelBuilder.Entity("Iemas.Domain.Reminders.ReminderPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("BusinessHoursEnd")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("BusinessHoursStart")
                        .HasColumnType("interval");

                    b.Property<Guid?>("ClassificationProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("EscalationThresholdReminderCount")
                        .HasColumnType("integer");

                    b.Property<bool>("ExcludeWeekends")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan?>("ExpirationWindow")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("InitialDelay")
                        .HasColumnType("interval");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxReminders")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("MinimumInterval")
                        .HasColumnType("interval");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<TimeSpan>("ReminderInterval")
                        .HasColumnType("interval");

                    b.Property<bool>("RestrictToBusinessHours")
                        .HasColumnType("boolean");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClassificationProfileId");

                    b.HasIndex("IsDefault");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("reminder_policies", (string)null);
                });

            modelBuilder.Entity("Iemas.Domain.Reminders.ReminderPolicyHoliday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<Guid>("ReminderPolicyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReminderPolicyId", "Date")
                        .IsUnique();

                    b.ToTable("reminder_policy_holidays", (string)null);
                });

            modelBuilder.Entity("Iemas.Domain.Agents.Agent", b =>
                {
                    b.HasOne("Iemas.Domain.Identity.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Iemas.Domain.Identity.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Iemas.Domain.Agents.AgentCaseAction", b =>
                {
                    b.HasOne("Iemas.Domain.Agents.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Iemas.Domain.Cases.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Iemas.Domain.Identity.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Case");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Iemas.Domain.Agents.AgentCredential", b =>
                {
                    b.HasOne("Iemas.Domain.Agents.Agent", "Agent")
                        .WithOne("Credential")
                        .HasForeignKey("Iemas.Domain.Agents.AgentCredential", "AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Iemas.Domain.Agents.AgentLog", b =>
                {
                    b.HasOne("Iemas.Domain.Agents.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Iemas.Domain.Ai.AiClassificationLog", b =>
                {
                    b.HasOne("Iemas.Domain.Email.EmailMessage", "EmailMessage")
                        .WithMany()
                        .HasForeignKey("EmailMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmailMessage");
                });

            modelBuilder.Entity("Iemas.Domain.Ai.EmailClassification", b =>
                {
                    b.HasOne("Iemas.Domain.Ai.ClassificationProfile", "ClassificationProfile")
                        .WithMany()
                        .HasForeignKey("ClassificationProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Iemas.Domain.Email.EmailMessage", "EmailMessage")
                        .WithOne()
                        .HasForeignKey("Iemas.Domain.Ai.EmailClassification", "EmailMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassificationProfile");

                    b.Navigation("EmailMessage");
                });

            modelBuilder.Entity("Iemas.Domain.Cases.Case", b =>
                {
                    b.HasOne("Iemas.Domain.Email.EmailAccount", "EmailAccount")
                        .WithMany()
                        .HasForeignKey("EmailAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Iemas.Domain.Identity.Employee", "OwnerEmployee")
                        .WithMany()
                        .HasForeignKey("OwnerEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EmailAccount");

                    b.Navigation("OwnerEmployee");
                });

            modelBuilder.Entity("Iemas.Domain.Cases.CaseEmail", b =>
                {
                    b.HasOne("Iemas.Domain.Cases.Case", "Case")
                        .WithMany("Emails")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Iemas.Domain.Email.EmailMessage", "EmailMessage")
                        .WithMany()
                        .HasForeignKey("EmailMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("EmailMessage");
                });

            modelBuilder.Entity("Iemas.Domain.Cases.CaseEvent", b =>
                {
                    b.HasOne("Iemas.Domain.Cases.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Iemas.Domain.Cases.ReplyVerificationAttempt", b =>
                {
                    b.HasOne("Iemas.Domain.Cases.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Iemas.Domain.Email.EmailAccount", b =>
                {
                    b.HasOne("Iemas.Domain.Identity.Employee", "OwnerEmployee")
                        .WithMany()
                        .HasForeignKey("OwnerEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OwnerEmployee");
                });

            modelBuilder.Entity("Iemas.Domain.Email.EmailAttachmentMetadata", b =>
                {
                    b.HasOne("Iemas.Domain.Email.EmailMessage", "EmailMessage")
                        .WithMany("Attachments")
                        .HasForeignKey("EmailMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmailMessage");
                });

            modelBuilder.Entity("Iemas.Domain.Email.EmailCredential", b =>
                {
                    b.HasOne("Iemas.Domain.Email.EmailAccount", "EmailAccount")
                        .WithOne("Credential")
                        .HasForeignKey("Iemas.Domain.Email.EmailCredential", "EmailAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmailAccount");
                });

            modelBuilder.Entity("Iemas.Domain.Email.EmailIntakeLog", b =>
                {
                    b.HasOne("Iemas.Domain.Email.EmailAccount", "EmailAccount")
                        .WithMany()
                        .HasForeignKey("EmailAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmailAccount");
                });

            modelBuilder.Entity("Iemas.Domain.Email.EmailMessage", b =>
                {
                    b.HasOne("Iemas.Domain.Email.EmailAccount", "EmailAccount")
                        .WithMany()
                        .HasForeignKey("EmailAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmailAccount");
                });

            modelBuilder.Entity("Iemas.Domain.Email.EmailSyncState", b =>
                {
                    b.HasOne("Iemas.Domain.Email.EmailAccount", "EmailAccount")
                        .WithMany()
                        .HasForeignKey("EmailAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmailAccount");
                });

            modelBuilder.Entity("Iemas.Domain.Escalations.EscalationEvent", b =>
                {
                    b.HasOne("Iemas.Domain.Cases.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Iemas.Domain.Escalations.EscalationPolicy", "EscalationPolicy")
                        .WithMany()
                        .HasForeignKey("EscalationPolicyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Case");

                    b.Navigation("EscalationPolicy");
                });

            modelBuilder.Entity("Iemas.Domain.Escalations.EscalationGroupMember", b =>
                {
                    b.HasOne("Iemas.Domain.Identity.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Iemas.Domain.Escalations.EscalationGroup", "EscalationGroup")
                        .WithMany("Members")
                        .HasForeignKey("EscalationGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("EscalationGroup");
                });

            modelBuilder.Entity("Iemas.Domain.Escalations.EscalationLevel", b =>
                {
                    b.HasOne("Iemas.Domain.Escalations.EscalationPolicy", "EscalationPolicy")
                        .WithMany("Levels")
                        .HasForeignKey("EscalationPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Iemas.Domain.Identity.Employee", "SpecificEmployee")
                        .WithMany()
                        .HasForeignKey("SpecificEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Iemas.Domain.Escalations.EscalationGroup", "SpecificGroup")
                        .WithMany()
                        .HasForeignKey("SpecificGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EscalationPolicy");

                    b.Navigation("SpecificEmployee");

                    b.Navigation("SpecificGroup");
                });

            modelBuilder.Entity("Iemas.Domain.Identity.Department", b =>
                {
                    b.HasOne("Iemas.Domain.Identity.Employee", "ManagerEmployee")
                        .WithMany()
                        .HasForeignKey("ManagerEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ManagerEmployee");
                });

            modelBuilder.Entity("Iemas.Domain.Identity.Employee", b =>
                {
                    b.HasOne("Iemas.Domain.Identity.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Iemas.Domain.Identity.Employee", "SupervisorEmployee")
                        .WithMany()
                        .HasForeignKey("SupervisorEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("SupervisorEmployee");
                });

            modelBuilder.Entity("Iemas.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("Iemas.Domain.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Iemas.Domain.Identity.User", b =>
                {
                    b.HasOne("Iemas.Domain.Identity.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Iemas.Domain.Identity.UserRole", b =>
                {
                    b.HasOne("Iemas.Domain.Identity.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Iemas.Domain.Identity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Iemas.Domain.Reminders.Reminder", b =>
                {
                    b.HasOne("Iemas.Domain.Cases.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Iemas.Domain.Reminders.ReminderPolicy", "ReminderPolicy")
                        .WithMany()
                        .HasForeignKey("ReminderPolicyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Case");

                    b.Navigation("ReminderPolicy");
                });

            modelBuilder.Entity("Iemas.Domain.Reminders.ReminderPolicyHoliday", b =>
                {
                    b.HasOne("Iemas.Domain.Reminders.ReminderPolicy", "ReminderPolicy")
                        .WithMany("Holidays")
                        .HasForeignKey("ReminderPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReminderPolicy");
                });

            modelBuilder.Entity("Iemas.Domain.Agents.Agent", b =>
                {
                    b.Navigation("Credential");
                });

            modelBuilder.Entity("Iemas.Domain.Cases.Case", b =>
                {
                    b.Navigation("Emails");
                });

            modelBuilder.Entity("Iemas.Domain.Email.EmailAccount", b =>
                {
                    b.Navigation("Credential");
                });

            modelBuilder.Entity("Iemas.Domain.Email.EmailMessage", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("Iemas.Domain.Escalations.EscalationGroup", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Iemas.Domain.Escalations.EscalationPolicy", b =>
                {
                    b.Navigation("Levels");
                });

            modelBuilder.Entity("Iemas.Domain.Identity.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Iemas.Domain.Identity.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Iemas.Domain.Identity.User", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Iemas.Domain.Reminders.ReminderPolicy", b =>
                {
                    b.Navigation("Holidays");
                });
#pragma warning restore 612, 618
        }
    }
}
