using Iemas.Domain.Common;

namespace Iemas.Domain.Agents;

/// <summary>
/// Requirements §70 — Agent Credential Requirements. Mirrors
/// <see cref="Iemas.Domain.Identity.RefreshToken"/>'s exact shape (opaque random value, only the
/// SHA-256 hash ever persisted, rotate-on-refresh) but FK'd to <see cref="Agent"/> instead of a
/// CMS <see cref="Iemas.Domain.Identity.User"/> — Agent auth is a deliberately separate credential
/// type, never a User/role-based login (§69).
///
/// Invariant this entity exists to enforce (§70): "Generated only by server. Unique per Agent.
/// Automatically provisioned. Never manually selected. Never generated by Agent. Rotatable.
/// Revocable. Invalid after revocation." The raw key is generated exactly once, server-side, at
/// approval time (<see cref="Application.Agents.AgentRegistrationService"/>) and is never
/// reconstructable from this row — only its hash lives here.
/// </summary>
public class AgentCredential : Entity
{
    public Guid AgentId { get; set; }
    public Agent Agent { get; set; } = null!;

    /// <summary>SHA-256 hash of the raw key — the only form ever used to verify an authentication attempt. The raw key itself is never stored anywhere in this form.</summary>
    public string KeyHash { get; set; } = string.Empty;
    public DateTimeOffset ExpiresAt { get; set; }
    public DateTimeOffset? RevokedAt { get; set; }
    public DateTimeOffset? RotatedAt { get; set; }

    /// <summary>
    /// §16-style "write-only after saving": the raw key, AES-256-GCM encrypted (same
    /// <see cref="Application.Common.Interfaces.ICredentialEncryptionService"/> used for mailbox
    /// credentials) so it is never plaintext at rest, held only transiently between approval and
    /// the Agent's single collection poll. Cleared (set to null) the moment it is collected — see
    /// <see cref="RawKeyCollected"/> — so even a database-level compromise after collection
    /// exposes nothing. Null once cleared; also null if the key was rotated (rotation follows the
    /// same collect-once contract via a fresh row's worth of these three fields).
    /// </summary>
    public byte[]? PendingKeyCiphertext { get; set; }
    public byte[]? PendingKeyNonce { get; set; }
    public byte[]? PendingKeyTag { get; set; }
    public string? PendingKeyEncryptionKeyId { get; set; }

    public bool RawKeyCollected { get; set; }

    public bool IsActive => RevokedAt is null && ExpiresAt > DateTimeOffset.UtcNow;
}
